// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Game.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Game _$GameFromJson(Map<String, dynamic> json) {
  return Game(
    (json['age_ratings'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['aggregated_rating'] as num?)?.toDouble(),
    json['aggregated_rating_count'] as int?,
    (json['alternative_names'] as List<dynamic>?)
        ?.map((e) => e as int)
        .toList(),
    (json['artworks'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['bundles'] as List<dynamic>?)?.map((e) => e as int).toList(),
    json['category'] as int?,
    json['checksum'] as String,
    json['collection'] as int?,
    json['cover'] as int?,
    json['created_at'] as int?,
    (json['dlcs'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['expanded_games'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['expansions'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['external_games'] as List<dynamic>?)?.map((e) => e as int).toList(),
    json['first_release'] as int?,
    json['follows'] as int?,
    (json['forks'] as List<dynamic>?)?.map((e) => e as int).toList(),
    json['franchise'] as int?,
    (json['franchises'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['game_engines'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['game_modes'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['genres'] as List<dynamic>?)?.map((e) => e as int).toList(),
    json['hypes'] as int?,
    json['id'] as int,
    (json['involved_companies'] as List<dynamic>?)
        ?.map((e) => e as int)
        .toList(),
    (json['keywords'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['multiplayer_modes'] as List<dynamic>?)
        ?.map((e) => e as int)
        .toList(),
    json['name'] as String,
    json['parent_game'] as int?,
    (json['platforms'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['player_perspectives'] as List<dynamic>?)
        ?.map((e) => e as int)
        .toList(),
    (json['posts'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['rating'] as num?)?.toDouble(),
    json['rating_count'] as int?,
    (json['release_dates'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['remakes'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['remasters'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['screenshots'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['similar_games'] as List<dynamic>?)?.map((e) => e as int).toList(),
    json['slug'] as String?,
    (json['standalone_expansions'] as List<dynamic>?)
        ?.map((e) => e as int)
        .toList(),
    json['status'] as int?,
    json['storyline'] as String?,
    json['summary'] as String,
    (json['tags'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['themes'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['total_rating'] as num?)?.toDouble(),
    json['total_rating_count'] as int?,
    json['updated_at'] as int?,
    json['url'] as String?,
    json['version_parent'] as int?,
    json['version_title'] as String?,
    (json['videos'] as List<dynamic>?)?.map((e) => e as int).toList(),
    (json['websites'] as List<dynamic>?)?.map((e) => e as int).toList(),
  );
}

Map<String, dynamic> _$GameToJson(Game instance) => <String, dynamic>{
      'age_ratings': instance.ageRatings,
      'aggregated_rating': instance.aggregatedRating,
      'aggregated_rating_count': instance.aggregatedRatingCount,
      'alternative_names': instance.alternativeNames,
      'artworks': instance.artworks,
      'bundles': instance.bundles,
      'category': instance.category,
      'checksum': instance.checksum,
      'collection': instance.collection,
      'cover': instance.cover,
      'created_at': instance.createdAt,
      'dlcs': instance.dlcs,
      'expanded_games': instance.expandedGames,
      'expansions': instance.expansions,
      'external_games': instance.externalGames,
      'first_release': instance.firstRelease,
      'follows': instance.follows,
      'forks': instance.forks,
      'franchise': instance.franchise,
      'franchises': instance.franchises,
      'game_engines': instance.gameEngines,
      'game_modes': instance.gameModes,
      'genres': instance.genres,
      'hypes': instance.hypes,
      'id': instance.id,
      'involved_companies': instance.involvedCompanies,
      'keywords': instance.keywords,
      'multiplayer_modes': instance.multiplayerModes,
      'name': instance.name,
      'parent_game': instance.parentGame,
      'platforms': instance.platforms,
      'player_perspectives': instance.playerPerspectives,
      'posts': instance.posts,
      'rating': instance.rating,
      'rating_count': instance.ratingCount,
      'release_dates': instance.releaseDates,
      'remakes': instance.remakes,
      'remasters': instance.remasters,
      'screenshots': instance.screenshots,
      'similar_games': instance.similarGames,
      'slug': instance.slug,
      'standalone_expansions': instance.standaloneExpansions,
      'status': instance.status,
      'storyline': instance.storyline,
      'summary': instance.summary,
      'tags': instance.tags,
      'themes': instance.themes,
      'total_rating': instance.totalRating,
      'total_rating_count': instance.totalRatingCount,
      'updated_at': instance.updatedAt,
      'url': instance.url,
      'version_parent': instance.versionParent,
      'version_title': instance.versionTitle,
      'videos': instance.videos,
      'websites': instance.websites,
    };
